### PR TITLE
Issue #83: Added tiered lockout system

### LINKED ISSUE #83: Add scalable lockout penalties for failing security questions
- [x] First lockout - Notification, 5 min lockout
- [x] Second lockout - Notification 30 min lockout
- [x] Third lockout - Notification, speak to admin, fully locked out.
- [x] After 2 weeks from last fail, autoreset

### PR DESCRIPTION
**Pull request by Peterburnett**
Closes #83

### CODE REVIEW

File: classes/task/clear_old_lockouts.php [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+        $period = get_config('tool_securityquestions', 'lockoutresetduration');
+        // If period is 0, pull out early and don't clear anyone.
+        if ($period === 0) {
+            return;
+        }
+
+        $timetoclear = time() - $period;
+        // Grab all records older than the lockout reset duration, where they are atleast tier 1.
+        $sqlfrag = "timefailed < :time AND tier > 0";
+        $records = $DB->get_records_select('tool_securityquestions_loc', $sqlfrag, array('time' => $timetoclear));
```
Comment (brendanheywood) [inline classes/task/clear_old_lockouts.php:76]: How about instead of a loc cleanup, instead of just timefailed, we also add a new column which is 'lockeduntil' and calculated at lockout time,

Then we never delete the lockout history and just query if there are any lockouts which are not expired

File: classes/event/user_locked.php [hunk 2]
```diff
@@ -44,13 +44,17 @@ class locked_out extends \core\event\base {
...
      */
-    public static function locked_out_event($user) {
+    public static function locked_out_event($user, $tier) {
 
         $data = array(
             'context' => \context_user::instance($user->id),
-            'other' => array ('userid' => $user->id)
+            'other' => array (
+                'userid' => $user->id,
+                'tier' => $tier
```
Comment (brendanheywood) [inline classes/event/user_locked.php:56]: I think this should have the absolute time they are locked out until, the tier could change over time is a little obscure by itself

File: classes/task/clear_old_lockouts.php (hunk 1 above)
Comment (Peterburnett) [reply classes/task/clear_old_lockouts.php:76]: This can instead be done even more cleanly during the lock initialisation check, where any expired locks can be cleared, and the user's lock will be treated as a new lock

File: classes/event/user_locked.php (hunk 2 above)
Comment (Peterburnett) [reply classes/event/user_locked.php]: Changed to absolute time in the logs.

File: classes/event/locked_out.php [hunk 3]
```diff
@@ -44,13 +44,17 @@ class locked_out extends \core\event\base {
      * Create instance of event.
      *
      * @param int $userid the userid of the User whos account was locked
+     * @param int $tier the tier the user just moved onto.
```
Comment (brendanheywood) [inline classes/event/locked_out.php:47]: out of date

File: classes/local/table_manager.php [hunk 4]
```diff
@@ -51,14 +53,22 @@ public static function get_lockout_table() {
...
-        $table->colclasses = array('centeralign', 'centeralign', 'centeralign', 'centeralign', 'centeralign');
+        $table->align = array('center', 'left', 'left', 'left', 'center', 'left');
 
         foreach ($lockedusers as $userrecord) {
             $user = $DB->get_record('user', array('id' => $userrecord->userid));
 
+            // Initialise the lock, to check for expired locks.
+            tool_securityquestions_initialise_lockout_counter($user);
+            // If lock was reset to 0, ignore this user.
+            if ($DB->get_field('tool_securityquestions_loc', 'tier', array('userid' => $user->id)) == 0) {
```
Comment (brendanheywood) [inline classes/local/table_manager.php:68]: is this dead code? it is filtered above

Comment (Peterburnett) [reply classes/local/table_manager.php:68]: So this just calls the initialiser, which will clear the lock if it is expired, and if it was cleared, it skips displaying this user, as they are no longer locked. This function probably needs a rename, to make it clear exactly what it does, after adding the expiry functionality

File: classes/event/locked_out.php (hunk 3 above)
Comment (Peterburnett) [reply classes/event/locked_out.php:47]: Nice catch

File: classes/local/table_manager.php (hunk 4 above)
Comment (Peterburnett) [reply classes/local/table_manager.php:68]: Renamed the function to refresh_lock_state, which is a little clearer what is actually being done when it's called

File: locallib.php [hunk 5]
```diff
@@ -653,26 +721,51 @@ function tool_securityquestions_is_locked_out($user) {
...
-    $DB->set_field('tool_securityquestions_loc', 'locked', 1, array('userid' => $user->id));
+    tool_securityquestions_refresh_lock_state($user);
+
+    // Set the new tier of lockout, never exceeding 3.
+    $origtier = $DB->get_field('tool_securityquestions_loc', 'tier', array('userid' => $user->id));
+    $newtier = $origtier < 3 ? $origtier + 1 : $origtier;
 
-    // Add event for logging locked user.
-    $event = \tool_securityquestions\event\locked_out::locked_out_event($user);
+    // Set the new tier, and reset the counter for that tier, then update timefailed.
```
Comment (brendanheywood) [inline locallib.php:730]: do these 3 lines in one update

File: locallib.php [hunk 6]
```diff
@@ -600,48 +636,80 @@ function tool_securityquestions_increment_lockout_counter($user) {
...
+ * It instantiates the lock record if the user does not have a record,
+ * And resets any expired lock records.
  *
  * @param stdClass $user the user to increment the counter of
  * @return bool returns true if user initialised, false if already present
  */
-function tool_securityquestions_initialise_lockout_counter($user) {
-    global $DB;
+function tool_securityquestions_refresh_lock_state($user) {
+    global $DB, $USER;
```
Comment (brendanheywood) [inline locallib.php:655]: remove $USER

File: locallib.php [hunk 7]
```diff
@@ -600,48 +636,80 @@ function tool_securityquestions_increment_lockout_counter($user) {
...
+ * This function ensures the lock record is fresh.
+ * It instantiates the lock record if the user does not have a record,
+ * And resets any expired lock records.
  *
  * @param stdClass $user the user to increment the counter of
  * @return bool returns true if user initialised, false if already present
  */
-function tool_securityquestions_initialise_lockout_counter($user) {
-    global $DB;
+function tool_securityquestions_refresh_lock_state($user) {
```
Comment (brendanheywood) [inline locallib.php:654]: this should return the lock record

File: locallib.php [hunk 8]
```diff
@@ -600,48 +636,80 @@ function tool_securityquestions_increment_lockout_counter($user) {
...
+        $DB->insert_record('tool_securityquestions_loc',
+            array('userid' => $user->id, 'tier' => 0, 'counter' => 0, 'timefailed' => 0));
         return true;
     } else {
+        // Now check for if user has a lockout that is expired, and reset it.
+        $record = $DB->get_record('tool_securityquestions_loc', array('userid' => $user->id));
+        $resetduration = get_config('tool_securityquestions', 'lockoutresetduration');
+        // Check if duration is 0, no resetting allowed.
+        if (($record->timefailed < time() - $resetduration) && $record->timefailed != 0 && $resetduration != 0) {
+            $DB->delete_records('tool_securityquestions_loc', array('userid' => $user->id));
```
Comment (brendanheywood) [inline locallib.php:669]: swap this to an record update to reset state

File: locallib.php [hunk 9]
```diff
@@ -600,48 +636,80 @@ function tool_securityquestions_increment_lockout_counter($user) {
...
+            // Now call this function again to create the record.
+            tool_securityquestions_refresh_lock_state($user);
```
Comment (brendanheywood) [inline locallib.php:671]: this should be redudnant

File: locallib.php [hunk 10]
```diff
@@ -600,48 +636,80 @@ function tool_securityquestions_increment_lockout_counter($user) {
...
-    $lock = $DB->get_field('tool_securityquestions_loc', 'locked', array('userid' => $user->id));
-    if ($lock) {
-        return true;
-    } else {
-        return false;
+    $tierone = get_config('tool_securityquestions', 'tieroneduration');
+    $tiertwo = get_config('tool_securityquestions', 'tiertwoduration');
+
+    // Now check the users tier, and compare times.
+    $record = $DB->get_record('tool_securityquestions_loc', array('userid' => $user->id));
```
Comment (brendanheywood) [inline locallib.php:698]: this will be returned from lock state

File: settings.php [hunk 11]
```diff
@@ -102,5 +102,17 @@
         $settings->add(new admin_setting_configtext('tool_securityquestions/lockoutnum',
                     get_string('settingslockoutnum', 'tool_securityquestions'),
                     get_string('settingslockoutnumdesc', 'tool_securityquestions'), 3, PARAM_INT));
+
```
Comment (brendanheywood) [inline settings.php:105]: add heading with extra paragraph of examples

change defaults to be off so we have feature parity with previous version
